### ISSUE TITLE
Logout button clears session storage first, then throws a bug - error in redirection

### ISSUE THREAD

**Issue by Ayuda-ai** [Ayuda-ai/ayuda_ui#6]
- When LOGOUT is clicked, it clears the session storage but before it redirects to Home Page, it throws error.
![Screenshot 2024-10-06 233352](https://github.com/user-attachments/assets/5201e89a-fdfa-48a1-b5f0-70b2f49dac1f)

- LOGOUT button must redirect to home page and clear session storage simultaneously

**Comment by Gizmosoft** [comment]
https://github.com/Ayuda-ai/ayuda_ui/pull/12

Issue resolved
