### ISSUE TITLE
Logout button not showing up as soon as login happens

### ISSUE THREAD

**Issue by Ayuda-ai** [Ayuda-ai/ayuda_ui#7]
Logout on the top right corner of the Navbar shows up only after you reload post LOGIN

**Comment by Gizmosoft** [comment]
https://github.com/Ayuda-ai/ayuda_ui/pull/12

Tried to resolve this issue along with Issue#6 in this PR but this issue is still persistent

**Comment by Gizmosoft** [comment]
Issue resolved. Raising a PR for fixing it.

**Comment by Gizmosoft** [comment]
Bug resolved
https://github.com/Ayuda-ai/ayuda_ui/pull/13
